CREATE TABLE IF NOT EXISTS roles
(id SERIAL PRIMARY KEY,
 name VARCHAR(64) UNIQUE);

 CREATE TABLE IF NOT EXISTS users
 (id SERIAL PRIMARY KEY,
 username VARCHAR(64) UNIQUE,
 role_id INT REFERENCES roles (id));